# Generated by Django 6.0.5 on 2026-05-22 08:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(choices=[('hero', 'Hero'), ('about', 'About'), ('core_services', 'Core Services'), ('why_choose_us', 'Why Choose Us'), ('approach', 'Approach'), ('cta', 'CTA')], max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Recommended: 800×600 px', upload_to='homepage/')),
                ('background_image', models.ImageField(blank=True, help_text='Recommended: 1920×1080 px', upload_to='homepage/')),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Section',
                'verbose_name_plural': 'Homepage Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='London International Academy for Excellence', max_length=200)),
                ('short_name', models.CharField(default='LIAFE', max_length=64)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, help_text='Recommended: 300×100 px', upload_to='logos/')),
                ('favicon', models.ImageField(blank=True, help_text='Recommended: 32×32 px', upload_to='logos/')),
                ('hero_background_image', models.ImageField(blank=True, help_text='Recommended: 1920×1080 px', upload_to='homepage/')),
                ('default_page_banner', models.ImageField(blank=True, help_text='Recommended: 1920×600 px', upload_to='banners/')),
                ('phone', models.CharField(default='+44 207 354 33 55', max_length=64)),
                ('email', models.EmailField(default='info@ukliafe.com', max_length=254)),
                ('address', models.CharField(default='London, N4 2DN', max_length=300)),
                ('working_hours', models.CharField(default='9 AM – 5 PM', max_length=120)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('footer_text', models.TextField(blank=True)),
                ('copyright_text', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='ValuePillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text="e.g. 'Knowledge' (matches frontend icon set)", max_length=64)),
                ('image', models.ImageField(blank=True, help_text='Recommended: 800×500 px', upload_to='general/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Value Pillar',
                'verbose_name_plural': 'Value Pillars',
                'ordering': ['order'],
            },
        ),
    ]
