# Generated by Django 6.0.5 on 2026-05-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, help_text='Recommended: 1920×1080 px', upload_to='hero/')),
                ('button_1_text', models.CharField(blank=True, default='Consult Us', max_length=100)),
                ('button_1_link', models.CharField(blank=True, default='/contact/', max_length=300)),
                ('button_2_text', models.CharField(blank=True, default='Explore Services', max_length=100)),
                ('button_2_link', models.CharField(blank=True, default='#services', max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order'],
            },
        ),
    ]
