# Generated by Django 6.0.5 on 2026-05-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. 12, 40, 25, £3.2', max_length=20)),
                ('suffix', models.CharField(blank=True, help_text='e.g. +, bn (leave blank if none)', max_length=10)),
                ('label', models.CharField(help_text='e.g. Markets Served', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'About Stat',
                'verbose_name_plural': 'About Stats',
                'ordering': ['order'],
            },
        ),
    ]
