# Generated by Django 6.0.5 on 2026-05-22 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly name, e.g. about-us', max_length=200, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, help_text='Recommended: 1200×630 px', upload_to='pages/')),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_menu', models.BooleanField(default=False, help_text='Add this page to the top navigation bar')),
                ('menu_label', models.CharField(blank=True, help_text='Short label in the nav (defaults to title)', max_length=100)),
                ('menu_order', models.PositiveSmallIntegerField(default=99)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Page',
                'verbose_name_plural': 'Custom Pages',
                'ordering': ['menu_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NavigationMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('external_url', models.CharField(blank=True, help_text='Used when no page is selected — e.g. /contact/', max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('page', models.ForeignKey(blank=True, help_text='Link to a custom page (leave blank to use External URL)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.custompage')),
            ],
            options={
                'verbose_name': 'Navigation Menu Item',
                'verbose_name_plural': 'Navigation Menu Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('text', 'Text Block'), ('image_text', 'Image + Text'), ('cards', 'Cards'), ('gallery', 'Gallery / Pictures'), ('cta', 'Call to Action'), ('faq', 'FAQ')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Recommended: 800×600 px', upload_to='pages/sections/')),
                ('background_image', models.ImageField(blank=True, help_text='Recommended: 1920×1080 px', upload_to='pages/backgrounds/')),
                ('background_color', models.CharField(blank=True, help_text='e.g. #F8FAFC (leave blank for white)', max_length=20)),
                ('image_position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=10)),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=300)),
                ('text_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center')], default='left', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.custompage')),
            ],
            options={
                'verbose_name': 'Page Section',
                'verbose_name_plural': 'Page Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(blank=True, help_text='e.g. Star, Globe, Shield', max_length=64)),
                ('image', models.ImageField(blank=True, help_text='Recommended: 600×400 px', upload_to='pages/items/')),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=300)),
                ('caption', models.CharField(blank=True, help_text='Caption shown below gallery images', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.pagesection')),
            ],
            options={
                'verbose_name': 'Section Item',
                'verbose_name_plural': 'Section Items',
                'ordering': ['order'],
            },
        ),
    ]
