# Generated by Django 6.0.5 on 2026-05-22 08:38

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('full_description', ckeditor.fields.RichTextField(blank=True)),
                ('icon_class', models.CharField(blank=True, max_length=64)),
                ('image', models.ImageField(blank=True, help_text='Recommended: 800×500 px', upload_to='academy/')),
                ('delivery_method', models.CharField(blank=True, max_length=64)),
                ('duration', models.CharField(blank=True, max_length=64)),
                ('level', models.CharField(blank=True, max_length=64)),
                ('button_text', models.CharField(blank=True, default='Learn More', max_length=64)),
                ('button_link', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResearchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('full_description', ckeditor.fields.RichTextField(blank=True)),
                ('icon_class', models.CharField(blank=True, max_length=64)),
                ('image', models.ImageField(blank=True, help_text='Recommended: 800×500 px', upload_to='research/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Research Category',
                'verbose_name_plural': 'Research Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('menu_title', models.CharField(blank=True, max_length=120)),
                ('icon_class', models.CharField(blank=True, help_text="e.g. 'Shariah', 'Academy'", max_length=64)),
                ('short_description', models.CharField(max_length=400)),
                ('full_description', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Recommended: 800×600 px', upload_to='services/')),
                ('hero_image', models.ImageField(blank=True, help_text='Recommended: 1920×1080 px', upload_to='services/')),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, max_length=300)),
                ('hero_description', models.TextField(blank=True)),
                ('cta_title', models.CharField(blank=True, max_length=200)),
                ('cta_description', models.TextField(blank=True)),
                ('cta_button_text', models.CharField(blank=True, max_length=100)),
                ('cta_button_link', models.CharField(blank=True, max_length=300)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=400)),
                ('full_description', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Recommended: 800×500 px', upload_to='academy/')),
                ('duration', models.CharField(blank=True, max_length=64)),
                ('delivery_method', models.CharField(blank=True, max_length=64)),
                ('level', models.CharField(blank=True, max_length=64)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('registration_link', models.URLField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='services.coursecategory')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('short_description', models.CharField(max_length=400)),
                ('full_description', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Recommended: 800×500 px', upload_to='research/')),
                ('research_status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('published', 'Published')], default='published', max_length=20)),
                ('client_or_partner', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, upload_to='research/reports/')),
                ('external_link', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='services.researchcategory')),
            ],
            options={
                'verbose_name': 'Research Project',
                'verbose_name_plural': 'Research Projects',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('full_description', ckeditor.fields.RichTextField(blank=True)),
                ('icon_class', models.CharField(blank=True, max_length=64)),
                ('image', models.ImageField(blank=True, help_text='Recommended: 800×500 px', upload_to='services/')),
                ('item_type', models.CharField(choices=[('process', 'Process Step'), ('card', 'Card')], default='card', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Feature',
                'verbose_name_plural': 'Service Features',
                'ordering': ['order'],
            },
        ),
    ]
