# Generated by Django 6.0.5 on 2026-05-22 08:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('publication_type', models.CharField(choices=[('book', 'Book'), ('article', 'Article'), ('report', 'Research Report'), ('journal', 'Journal Paper'), ('thought', 'Thought Leadership'), ('other', 'Other')], max_length=20)),
                ('author', models.CharField(max_length=200)),
                ('co_authors', models.CharField(blank=True, max_length=400)),
                ('short_description', models.CharField(max_length=400)),
                ('full_description', ckeditor.fields.RichTextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Recommended: 600×900 px', upload_to='publications/covers/')),
                ('pdf_file', models.FileField(blank=True, upload_to='publications/pdfs/')),
                ('external_link', models.URLField(blank=True)),
                ('isbn', models.CharField(blank=True, max_length=64)),
                ('doi', models.CharField(blank=True, max_length=128)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['order', '-published_date'],
            },
        ),
    ]
